HTTP_CODE_MSG_ERROR = "Ожидаемый http-код - {}, фактический - {}"
RESPONSE_BODY_LIST_LENGTH_MSG_ERROR = "Ожидалось {} элементов в ответе, но получено {}"
RESPONSE_NOT_JSON_MSG_ERROR = "Ответ не является корректным JSON"
RESPONSE_BODY_NOT_EMPTY_MSG_ERROR = "Ожидалось, что тело ответа будет отсутствовать"
RESPONSE_BODY_IS_EMPTY_MSG_ERROR = "Тело ответа отсутствует"
